# imports

In [53]:
import pandas as pd

## import dataset

In [54]:
df = pd.read_csv("bread-basket.csv")

## dataset information

In [55]:
df.columns

Index(['Transaction', 'Item', 'date_time', 'period_day', 'weekday_weekend'], dtype='object')

## Data Preprocessing

In [56]:
df.info

<bound method DataFrame.info of        Transaction           Item         date_time period_day weekday_weekend
0                1          Bread  30-10-2016 09:58    morning         weekend
1                2   Scandinavian  30-10-2016 10:05    morning         weekend
2                2   Scandinavian  30-10-2016 10:05    morning         weekend
3                3  Hot chocolate  30-10-2016 10:07    morning         weekend
4                3            Jam  30-10-2016 10:07    morning         weekend
...            ...            ...               ...        ...             ...
20502         9682         Coffee  09-04-2017 14:32  afternoon         weekend
20503         9682            Tea  09-04-2017 14:32  afternoon         weekend
20504         9683         Coffee  09-04-2017 14:57  afternoon         weekend
20505         9683         Pastry  09-04-2017 14:57  afternoon         weekend
20506         9684      Smoothies  09-04-2017 15:04  afternoon         weekend

[20507 rows x 5 columns]>

In [57]:
df.dtypes

Transaction         int64
Item               object
date_time          object
period_day         object
weekday_weekend    object
dtype: object

In [58]:
df.describe()

        Transaction
count  20507.000000
mean    4976.202370
std     2796.203001
min        1.000000
25%     2552.000000
50%     5137.000000
75%     7357.000000
max     9684.000000

In [59]:
null_counts = df.isnull().sum()
print(null_counts)

Transaction        0
Item               0
date_time          0
period_day         0
weekday_weekend    0
dtype: int64

In [60]:
# fixing date time format
df['date_time'] = pd.to_datetime(df['date_time'])

C:\Users\Moussa\AppData\Local\Temp\ipykernel_21464\3264271555.py:2: UserWarning: Parsing dates in %d-%m-%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['date_time'] = pd.to_datetime(df['date_time'])

In [61]:
df

,Transaction,Item,date_time,period_day,weekday_weekend
0,1,Bread,2016-10-30 09:58:00,morning,weekend
1,2,Scandinavian,2016-10-30 10:05:00,morning,weekend
2,2,Scandinavian,2016-10-30 10:05:00,morning,weekend
3,3,Hot chocolate,2016-10-30 10:07:00,morning,weekend
4,3,Jam,2016-10-30 10:07:00,morning,weekend
...,...,...,...,...,...
20502,9682,Coffee,2017-04-09 14:32:00,afternoon,weekend
20503,9682,Tea,2017-04-09 14:32:00,afternoon,weekend
20504,9683,Coffee,2017-04-09 14:57:00,afternoon,weekend
20505,9683,Pastry,2017-04-09 14:57:00,afternoon,weekend
20506,9684,Smoothies,2017-04-09 15:04:00,afternoon,weekend

   Transaction           date_time period_day weekday_weekend  \
0            1 2016-10-30 09:58:00    morning         weekend
1            2 2016-10-30 10:05:00    morning         weekend
2            2 2016-10-30 10:05:00    morning         weekend
3            3 2016-10-30 10:07:00    morning         weekend
4            3 2016-10-30 10:07:00    morning         weekend

   Item_Adjustment  Item_Afternoon with the baker  Item_Alfajores  \
0            False                          False           False
1            False                          False           False
2            False                          False           False
3            False                          False           False
4            False                          False           False

   Item_Argentina Night  Item_Art Tray  Item_Bacon  ...  Item_The BART  \
0                 False          False       False  ...          False
1                 False          False       False  ...          False
2                 False          False       False  ...          False
3                 False          False       False  ...          False
4                 False          False       False  ...          False

   Item_The Nomad  Item_Tiffin  Item_Toast  Item_Truffles  Item_Tshirt  \
0           False        False       False          False        False
1           False        False       False          False        False
2           False        False       False          False        False
3           False        False       False          False        False
4           False        False       False          False        False

   Item_Valentine's card  Item_Vegan Feast  Item_Vegan mincepie  \
0                  False             False                False
1                  False             False                False
2                  False             False                False
3                  False             False                False
4                  False             False                False

   Item_Victorian Sponge
0                  False
1                  False
2                  False
3                  False
4                  False

[5 rows x 98 columns]

c:\Users\Moussa\AppData\Local\Programs\Python\Python312\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

ValueError: The allowed values for a DataFrame are True, False, 0, 1. Found value 2016-10-30 09:58:00